import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // 以前は dirName: '.' の1本で docs/ 配下すべて(生活サーバー・マイクラ人狼・利用規約・
    // お問い合わせ)を1つのサイドバーに詰め込んでいたため、無関係な項目が並んでしまい
    // 見通しが悪かった。ナビバー側で案内先を分けられるよう、内容ごとに
    // サイドバーを分割する(参考: React Native/Jest/Ionic等の複数ドキュメント群サイト)。
    // 各サイドバー内の並び順は、既存の _category_.json / frontmatter の position をそのまま使う。
    livingSidebar: [{type: 'autogenerated', dirName: 'living'}],
    wolfSidebar: [{type: 'autogenerated', dirName: 'wolf'}],
    tosSidebar: [{type: 'autogenerated', dirName: 'tos'}],
};

export default sidebars;
